version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "lockfile-only"
    groups:
      dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "rust"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"
